/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...404]': RouteRecordInfo<'/[...404]', '/:404(.*)', { 404: ParamValue<true> }, { 404: ParamValue<false> }>,
    '/about': RouteRecordInfo<'/about', '/about', Record<never, never>, Record<never, never>>,
    '/daily/': RouteRecordInfo<'/daily/', '/daily', Record<never, never>, Record<never, never>>,
    '/daily/[date]': RouteRecordInfo<'/daily/[date]', '/daily/:date', { date: ParamValue<true> }, { date: ParamValue<false> }>,
    '/daily/2026-04-10': RouteRecordInfo<'/daily/2026-04-10', '/daily/2026-04-10', Record<never, never>, Record<never, never>>,
    '/daily/2026-04-11': RouteRecordInfo<'/daily/2026-04-11', '/daily/2026-04-11', Record<never, never>, Record<never, never>>,
    '/daily/2026-04-14': RouteRecordInfo<'/daily/2026-04-14', '/daily/2026-04-14', Record<never, never>, Record<never, never>>,
    '/posts/Axure-RP11-快捷键完全指南': RouteRecordInfo<'/posts/Axure-RP11-快捷键完全指南', '/posts/Axure-RP11-快捷键完全指南', Record<never, never>, Record<never, never>>,
    '/posts/building-effective-agents': RouteRecordInfo<'/posts/building-effective-agents', '/posts/building-effective-agents', Record<never, never>, Record<never, never>>,
    '/posts/koa': RouteRecordInfo<'/posts/koa', '/posts/koa', Record<never, never>, Record<never, never>>,
    '/posts/llm-customization-methods-complete-guide': RouteRecordInfo<'/posts/llm-customization-methods-complete-guide', '/posts/llm-customization-methods-complete-guide', Record<never, never>, Record<never, never>>,
    '/posts/oauth-2.0': RouteRecordInfo<'/posts/oauth-2.0', '/posts/oauth-2/0', Record<never, never>, Record<never, never>>,
    '/posts/React开发过程中需要注意的点': RouteRecordInfo<'/posts/React开发过程中需要注意的点', '/posts/React开发过程中需要注意的点', Record<never, never>, Record<never, never>>,
    '/posts/React整体架构': RouteRecordInfo<'/posts/React整体架构', '/posts/React整体架构', Record<never, never>, Record<never, never>>,
    '/posts/React渲染流程': RouteRecordInfo<'/posts/React渲染流程', '/posts/React渲染流程', Record<never, never>, Record<never, never>>,
    '/posts/React组件渲染性能优化': RouteRecordInfo<'/posts/React组件渲染性能优化', '/posts/React组件渲染性能优化', Record<never, never>, Record<never, never>>,
    '/posts/产品经理的学习网站和常用工具': RouteRecordInfo<'/posts/产品经理的学习网站和常用工具', '/posts/产品经理的学习网站和常用工具', Record<never, never>, Record<never, never>>,
    '/posts/常见数据报告来源': RouteRecordInfo<'/posts/常见数据报告来源', '/posts/常见数据报告来源', Record<never, never>, Record<never, never>>,
    '/posts/幕后产品': RouteRecordInfo<'/posts/幕后产品', '/posts/幕后产品', Record<never, never>, Record<never, never>>,
    '/posts/新人需要掌握的产品专业词汇': RouteRecordInfo<'/posts/新人需要掌握的产品专业词汇', '/posts/新人需要掌握的产品专业词汇', Record<never, never>, Record<never, never>>,
    '/posts/用 skill-creator 创建新 skill 的流程记录': RouteRecordInfo<'/posts/用 skill-creator 创建新 skill 的流程记录', '/posts/用 skill-creator 创建新 skill 的流程记录', Record<never, never>, Record<never, never>>,
    '/posts/社交类产品设计': RouteRecordInfo<'/posts/社交类产品设计', '/posts/社交类产品设计', Record<never, never>, Record<never, never>>,
    '/posts/社区类产品设计': RouteRecordInfo<'/posts/社区类产品设计', '/posts/社区类产品设计', Record<never, never>, Record<never, never>>,
    '/posts/虚拟DOM': RouteRecordInfo<'/posts/虚拟DOM', '/posts/虚拟DOM', Record<never, never>, Record<never, never>>,
    '/posts/行业与竞品分析': RouteRecordInfo<'/posts/行业与竞品分析', '/posts/行业与竞品分析', Record<never, never>, Record<never, never>>,
    '/posts/解构是使用对象还是数组': RouteRecordInfo<'/posts/解构是使用对象还是数组', '/posts/解构是使用对象还是数组', Record<never, never>, Record<never, never>>,
    '/product/': RouteRecordInfo<'/product/', '/product', Record<never, never>, Record<never, never>>,
    '/product/for-today-miniprogram': RouteRecordInfo<'/product/for-today-miniprogram', '/product/for-today-miniprogram', Record<never, never>, Record<never, never>>,
    '/product/fview-power': RouteRecordInfo<'/product/fview-power', '/product/fview-power', Record<never, never>, Record<never, never>>,
    '/thinking/': RouteRecordInfo<'/thinking/', '/thinking', Record<never, never>, Record<never, never>>,
  }
}
